# Generated by Django 3.2.3 on 2021-10-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20211016_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderupdate',
            name='items_json',
        ),
        migrations.RemoveField(
            model_name='orderupdate',
            name='name',
        ),
        migrations.AlterField(
            model_name='orderupdate',
            name='order_id',
            field=models.IntegerField(default=''),
        ),
    ]
